### ISSUE TITLE
No obvious way to configure email recipients

### ISSUE THREAD

**Issue by cargocultprogramming** [cosmocode/dokuwiki-plugin-structpublish#13]
Maybe I'm missing something, but I cant see a way to specify recipients for emails.

There is an option to activate "status changes that trigger emails" however, I don't see a way to specify where these notifications should be send. Consequently I get an error "Got 503 5.5.2 Need rcpt command" - I assume that this is due to the recipient missing.

Not sure how to proceed.

**Comment by binauchhier** [comment]
With us, if you check both checkboxes, the mails are sent to the person(s) who is/are allowed to publish a specific page, if you click on "approve".

Maybe you configuration for SMTP is wrong?

**Comment by annda** [comment]
As the documentation says:

> You may notify users who are assigned to the next due workflow step.

This is exactly what @binauchhier describes. There is no need to configure recipients.

When you google your error message, it will point you to possible mail server problems and solutions.
