### ISSUE TITLE
TOC missing if latest version not released

### ISSUE THREAD

**Issue by binauchhier** [cosmocode/dokuwiki-plugin-structpublish#18]
### Issue Description

If there is a released version of a page, but it has already been revised but this revision is not yet published, all users without approve or publish rights will not see a table of contents on this page. 
The Table of contents is visible if the latest revision is published.

Using sprintdoc with the latest versions of all plugins.

**Comment by annda** [comment]
This is actually a bug in the SprintDoc template. I have just created an [issue](https://github.com/cosmocode/dokuwiki-template-sprintdoc/issues/109) with the problem you have reported
