### ISSUE TITLE
No mails are sent

### ISSUE THREAD

**Issue by Nils98Ar** [cosmocode/dokuwiki-plugin-structpublish#19]
### Issue Description

Users in the groups `@approver` and `@publisher` do not receive mails although mailing is enabled and groups are assigned for namespaces.

```
grep -ri structpublish conf/local.php
$conf['plugin']['structpublish']['email_enable'] = 1;
$conf['plugin']['structpublish']['email_status'] = 'approve,publish';
```

```
sqlite> select * from structpublish_assignments_patterns;
pattern|user|status
<namespacexy>:*|@approver|approve
<namespacexy>:*|@publisher|publish
```

Passwort reset mails from Dokuwiki are working.

I cannot see errors in the browser console or in the webserver `error.log`. Any idea how to debug this?

**Comment by Nils98Ar** [comment]
Seems that `$in` is `NULL` here.
```
grep "public function changeStatus" lib/plugins/structpublish/action/publish.php -A8
    public function changeStatus(Doku_Event $event)
    {
        if ($event->data != 'show') {
            return;
        }

        global $INPUT;

        $in = $INPUT->arr('structpublish');
```

**Comment by Nils98Ar** [comment]
The second argument `0` for the retrieveUsers method seems to be the problem as this limits the output to zero items instead of unlimited.

```
grep "function resolveGroup" lib/plugins/structpublish/helper/notify.php -A9
    protected function resolveGroup(&$resolved, $recipient)
    {

        /** @var AuthPlugin $auth */
        global $auth;
        if (!$auth->canDo('getUsers')) {
            throw new \Exception('Auth cannot fetch users by group.');
        }

        $users = $auth->retrieveUsers(0, 0, ['grps' => substr($recipient, 1)]);
```

**Comment by Nils98Ar** [comment]
Could be a problem with `authpdo` which we use. 

Propably we could use a similar workaround as here?
https://github.com/cosmocode/dokuwiki-plugin-submgr/commit/6e00edb2cf211a354e9ec0d66cf0dfefe5a83ffc

**Comment by annda** [comment]
@Nils98Ar Thank you for the thorough research. The latest commit should fix your problem.
